import * as HybridAppActions from '@libs/actions/HybridApp';

import ONYXKEYS from '@src/ONYXKEYS';
// jest.mock is hoisted, so this connect runs with IS_HYBRID_APP already true.
import '@libs/HybridApp';

import type {TryNewDot} from '@src/types/onyx';

import HybridAppModule from '@expensify/react-native-hybrid-app';
import Onyx from 'react-native-onyx';

import getOnyxValue from '../utils/getOnyxValue';
import waitForBatchedUpdates from '../utils/waitForBatchedUpdates';

jest.mock('@src/CONFIG', () => {
    const actualConfig = jest.requireActual<{default: Record<string, unknown>}>('@src/CONFIG').default;
    return {
        __esModule: true,
        default: {...actualConfig, IS_HYBRID_APP: true},
    };
});

const classicRedirect = {
    dismissed: true,
    timestamp: new Date(),
    completedHybridAppOnboarding: true,
};

async function settleSignIn({tryNewDot, needsTwoFactorAuthSetup, requiresTwoFactorAuth}: {tryNewDot: TryNewDot; needsTwoFactorAuthSetup: boolean; requiresTwoFactorAuth: boolean}) {
    await Onyx.multiSet({
        [ONYXKEYS.HYBRID_APP]: {useNewDotSignInPage: true},
        [ONYXKEYS.CREDENTIALS]: {autoGeneratedLogin: 'device-login', autoGeneratedPassword: 'device-password'},
        [ONYXKEYS.SESSION]: {authToken: 'auth-token', accountID: 1, email: 'user@expensify.com'},
        [ONYXKEYS.ACCOUNT]: {needsTwoFactorAuthSetup, requiresTwoFactorAuth},
        [ONYXKEYS.NVP_TRY_NEW_DOT]: tryNewDot,
    });
    await waitForBatchedUpdates();
    await waitForBatchedUpdates();
}

describe('HybridApp sign-in experience', () => {
    let closeNativeAppSpy: jest.SpiedFunction<typeof HybridAppModule.closeReactNativeApp>;

    beforeEach(async () => {
        closeNativeAppSpy = jest.spyOn(HybridAppModule, 'closeReactNativeApp').mockImplementation(() => {});
        jest.spyOn(HybridAppModule, 'signInToOldDot').mockImplementation(() => {});
        await Onyx.clear();
        await waitForBatchedUpdates();
    });

    afterEach(() => {
        jest.restoreAllMocks();
    });

    it('keeps a Classic user in NewDot and stores the hold while required 2FA is pending', async () => {
        await settleSignIn({
            tryNewDot: {classicRedirect},
            needsTwoFactorAuthSetup: true,
            requiresTwoFactorAuth: false,
        });

        const hybridApp = await getOnyxValue(ONYXKEYS.HYBRID_APP);
        expect(hybridApp?.shouldReturnToOldDotAfter2FA).toBe(true);
        expect(hybridApp?.readyToShowAuthScreens).toBe(true);
        expect(closeNativeAppSpy).not.toHaveBeenCalled();
    });

    it('stores the hold when classicRedirect is empty, which sign-in treats as Classic', async () => {
        await settleSignIn({
            tryNewDot: {},
            needsTwoFactorAuthSetup: true,
            requiresTwoFactorAuth: false,
        });

        const hybridApp = await getOnyxValue(ONYXKEYS.HYBRID_APP);
        expect(hybridApp?.shouldReturnToOldDotAfter2FA).toBe(true);
        expect(closeNativeAppSpy).not.toHaveBeenCalled();
    });

    it('closes NewDot for a Classic user who does not still need 2FA, and leaves the hold unset', async () => {
        await settleSignIn({
            tryNewDot: {classicRedirect},
            needsTwoFactorAuthSetup: false,
            requiresTwoFactorAuth: true,
        });

        const hybridApp = await getOnyxValue(ONYXKEYS.HYBRID_APP);
        expect(hybridApp?.shouldReturnToOldDotAfter2FA).toBe(false);
        expect(closeNativeAppSpy).toHaveBeenCalledWith({shouldSetNVP: false});
    });

    it('does not store a hold for a NewDot user, even when 2FA setup is pending', async () => {
        await settleSignIn({
            tryNewDot: {classicRedirect: {...classicRedirect, dismissed: false}},
            needsTwoFactorAuthSetup: true,
            requiresTwoFactorAuth: false,
        });

        const hybridApp = await getOnyxValue(ONYXKEYS.HYBRID_APP);
        expect(hybridApp?.shouldReturnToOldDotAfter2FA).toBe(false);
        expect(hybridApp?.readyToShowAuthScreens).toBe(true);
        expect(closeNativeAppSpy).not.toHaveBeenCalled();
    });

    it('clears the hold on sign-out', async () => {
        await Onyx.merge(ONYXKEYS.HYBRID_APP, {shouldReturnToOldDotAfter2FA: true, useNewDotSignInPage: false});
        await waitForBatchedUpdates();

        await HybridAppActions.resetSignInFlow();
        await waitForBatchedUpdates();

        const hybridApp = await getOnyxValue(ONYXKEYS.HYBRID_APP);
        expect(hybridApp?.shouldReturnToOldDotAfter2FA).toBe(false);
        expect(hybridApp?.useNewDotSignInPage).toBe(true);
    });
});
